apiVersion: v1
kind: Namespace
metadata:
  name: gip

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: gip

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gip-role
  namespace: gip
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - pods
      - secrets
      - componentstatuses
      - daemonsets
      - deployments
      - events
      - endpoints
      - ingress
      - jobs
      - limitranges
      - nodes
      - horizontalpodautoscalers
      - namespaces
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: gip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gip-role
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: gip

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
 name: mysecretname
 namespace: gip
 annotations:
   kubernetes.io/service-account.name: jenkins
